### ISSUE TITLE
Make a folder automatically for each anime

### ISSUE THREAD

**Issue by B0SEmc** [colonel260/Anime-Downloader#5]

**Comment by 0ri0nexe** [comment]
Hi ! Have you a valid URL for testing ?

**Comment by B0SEmc** [comment]
Hey! Since this uses yt-dlp you could use any youtube video URL like this one for exemple: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by 0ri0nexe** [comment]
yeah one more view for Rick Roll ;-;
