### ISSUE TITLE
Fix download directory for Mac OS and Linux file system

### ISSUE THREAD

**Issue by Fairy-Jeux** [colonel260/Anime-Downloader#8]

**Comment by Fairy-Jeux** [comment]
Download directory dosn't work with the MacOS file System

**Comment by B0SEmc** [comment]
There seems to be an issue on Linux too, it doesn't detect the anime getting downloaded. Moreover, it simply crashes on the debug build.

**Comment by B0SEmc** [comment]
Fixed.
